/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen2p2_edgarmembreno;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarmembreno
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_Esambladores = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        id_Esamblador = new javax.swing.JTextField();
        nombre_Esamblador = new javax.swing.JTextField();
        genero_Esamblador = new javax.swing.JTextField();
        edad_Esamblador = new javax.swing.JTextField();
        AgregarEnsamblador = new javax.swing.JButton();
        Jd_Bateria = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        material_Bateria = new javax.swing.JTextField();
        autonomia_Bateria = new javax.swing.JTextField();
        tiempo_Bateria = new javax.swing.JTextField();
        agregar_Bateria = new javax.swing.JButton();
        jd_Carroceria = new javax.swing.JDialog();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tipo_carroceria = new javax.swing.JTextField();
        tiempo_carroceria = new javax.swing.JTextField();
        maletero_capacidad = new javax.swing.JTextField();
        agregar_Carroceria = new javax.swing.JButton();
        jd_Interior = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        material_Interior = new javax.swing.JTextField();
        Volante_Interior = new javax.swing.JTextField();
        botones_Interior = new javax.swing.JTextField();
        tiempo_interior = new javax.swing.JTextField();
        agregar_Interior = new javax.swing.JButton();
        jd_Audio = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        pantallas_Infoentre = new javax.swing.JTextField();
        ancho_infoentre = new javax.swing.JTextField();
        tiempo_infoentre = new javax.swing.JTextField();
        agregar_Infoentretenimiento = new javax.swing.JButton();
        si = new javax.swing.JRadioButton();
        no = new javax.swing.JRadioButton();
        jd_asientos = new javax.swing.JDialog();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        caja_Asientos = new javax.swing.JTextField();
        material_Asientos = new javax.swing.JTextField();
        masaje_Asientos = new javax.swing.JTextField();
        tiempo_Asientos = new javax.swing.JTextField();
        Agregar_Asientos = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jd_CrearCarro = new javax.swing.JDialog();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jt_Bateria = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        jt_Inferior = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        jt_Carroceria = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        vin_vehiculo = new javax.swing.JTextField();
        marca_Audio = new javax.swing.JTextField();
        color_vehiculo = new javax.swing.JTextField();
        asientos_Vehiculo = new javax.swing.JTextField();
        AgregarCarro = new javax.swing.JButton();
        jd_Esamblar = new javax.swing.JDialog();
        jScrollPane9 = new javax.swing.JScrollPane();
        jt_Vehiculo = new javax.swing.JTable();
        jScrollPane10 = new javax.swing.JScrollPane();
        jt_Esamblador = new javax.swing.JTable();
        jLabel41 = new javax.swing.JLabel();
        esamblar_Carro = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        HiloEsamblar = new javax.swing.JDialog();
        prog_Esamblar = new javax.swing.JProgressBar();
        jLabel42 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Crearvehicuos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ListaDeVehiculos = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        jLabel5.setText("Esamblador");

        jLabel6.setText("ID");

        jLabel7.setText("Nombre");

        jLabel8.setText("Genero");

        jLabel9.setText("Edad");

        edad_Esamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edad_EsambladorActionPerformed(evt);
            }
        });

        AgregarEnsamblador.setText("Agregar");
        AgregarEnsamblador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEnsambladorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_EsambladoresLayout = new javax.swing.GroupLayout(jd_Esambladores.getContentPane());
        jd_Esambladores.getContentPane().setLayout(jd_EsambladoresLayout);
        jd_EsambladoresLayout.setHorizontalGroup(
            jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EsambladoresLayout.createSequentialGroup()
                .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jd_EsambladoresLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jd_EsambladoresLayout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel6))
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(id_Esamblador)
                            .addComponent(nombre_Esamblador)
                            .addComponent(genero_Esamblador)
                            .addComponent(edad_Esamblador, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)))
                    .addGroup(jd_EsambladoresLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel5)))
                .addContainerGap(164, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_EsambladoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(AgregarEnsamblador)
                .addGap(57, 57, 57))
        );
        jd_EsambladoresLayout.setVerticalGroup(
            jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EsambladoresLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(id_Esamblador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(nombre_Esamblador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(genero_Esamblador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_EsambladoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(edad_Esamblador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(AgregarEnsamblador)
                .addGap(24, 24, 24))
        );

        jLabel10.setText("Bateria");

        jLabel11.setText("Autonomia");

        jLabel12.setText("Material");

        jLabel13.setText("Tiempo");

        agregar_Bateria.setText("Agregar");
        agregar_Bateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_BateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Jd_BateriaLayout = new javax.swing.GroupLayout(Jd_Bateria.getContentPane());
        Jd_Bateria.getContentPane().setLayout(Jd_BateriaLayout);
        Jd_BateriaLayout.setHorizontalGroup(
            Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jd_BateriaLayout.createSequentialGroup()
                .addGroup(Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Jd_BateriaLayout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jLabel10))
                    .addGroup(Jd_BateriaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Jd_BateriaLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiempo_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jd_BateriaLayout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                                .addComponent(autonomia_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Jd_BateriaLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(material_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(109, 109, 109))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Jd_BateriaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_Bateria)
                .addGap(95, 95, 95))
        );
        Jd_BateriaLayout.setVerticalGroup(
            Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Jd_BateriaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel10)
                .addGap(48, 48, 48)
                .addGroup(Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(autonomia_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(material_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(Jd_BateriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(tiempo_Bateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(agregar_Bateria)
                .addGap(32, 32, 32))
        );

        jLabel14.setText("Carroceria");

        jLabel15.setText("Tipo");

        jLabel16.setText("Capacidad Maletero");

        jLabel17.setText("tiempo");

        agregar_Carroceria.setText("Agregar");
        agregar_Carroceria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_CarroceriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CarroceriaLayout = new javax.swing.GroupLayout(jd_Carroceria.getContentPane());
        jd_Carroceria.getContentPane().setLayout(jd_CarroceriaLayout);
        jd_CarroceriaLayout.setHorizontalGroup(
            jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                .addGroup(jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addComponent(jLabel14))
                    .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipo_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addComponent(maletero_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiempo_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(93, 93, 93))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CarroceriaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(agregar_Carroceria)
                .addGap(43, 43, 43))
        );
        jd_CarroceriaLayout.setVerticalGroup(
            jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CarroceriaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel14)
                .addGap(28, 28, 28)
                .addGroup(jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tipo_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(maletero_capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jd_CarroceriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(tiempo_carroceria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(agregar_Carroceria)
                .addGap(18, 18, 18))
        );

        jLabel18.setText("Interior");

        jLabel19.setText("Material");

        jLabel20.setText("Volante");

        jLabel21.setText("Cantidad de Botones");

        jLabel22.setText("Tiempo ");

        agregar_Interior.setText("Agregar");
        agregar_Interior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_InteriorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_InteriorLayout = new javax.swing.GroupLayout(jd_Interior.getContentPane());
        jd_Interior.getContentPane().setLayout(jd_InteriorLayout);
        jd_InteriorLayout.setHorizontalGroup(
            jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_InteriorLayout.createSequentialGroup()
                .addGroup(jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_InteriorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(agregar_Interior))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_InteriorLayout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(jLabel18)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_InteriorLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_InteriorLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Volante_Interior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_InteriorLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(material_Interior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_InteriorLayout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tiempo_interior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jd_InteriorLayout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                                .addComponent(botones_Interior, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(100, 100, 100))
        );
        jd_InteriorLayout.setVerticalGroup(
            jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_InteriorLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel18)
                .addGap(32, 32, 32)
                .addGroup(jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(material_Interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Volante_Interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(botones_Interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_InteriorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(tiempo_interior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(agregar_Interior)
                .addGap(39, 39, 39))
        );

        jLabel23.setText("Infoentretenimiento");

        jLabel24.setText("Cantidad Pantallas");

        jLabel25.setText("Visor");

        jLabel26.setText("Ancho de Pantalla");

        jLabel27.setText("Tiempo");

        agregar_Infoentretenimiento.setText("Agregar");
        agregar_Infoentretenimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregar_InfoentretenimientoActionPerformed(evt);
            }
        });

        buttonGroup1.add(si);
        si.setText("Si");
        si.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siActionPerformed(evt);
            }
        });

        buttonGroup1.add(no);
        no.setText("No");

        javax.swing.GroupLayout jd_AudioLayout = new javax.swing.GroupLayout(jd_Audio.getContentPane());
        jd_Audio.getContentPane().setLayout(jd_AudioLayout);
        jd_AudioLayout.setHorizontalGroup(
            jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AudioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(agregar_Infoentretenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(jd_AudioLayout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_AudioLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jd_AudioLayout.createSequentialGroup()
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tiempo_infoentre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jd_AudioLayout.createSequentialGroup()
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ancho_infoentre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_AudioLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addGap(142, 142, 142)
                            .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(si)
                                .addComponent(pantallas_Infoentre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(no)
                .addGap(178, 178, 178))
        );
        jd_AudioLayout.setVerticalGroup(
            jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_AudioLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel23)
                .addGap(45, 45, 45)
                .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(pantallas_Infoentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(si)
                    .addComponent(no))
                .addGap(18, 18, 18)
                .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(ancho_infoentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_AudioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(tiempo_infoentre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(agregar_Infoentretenimiento)
                .addGap(50, 50, 50))
        );

        jLabel28.setText("Asientos");

        jLabel29.setText("Material");

        jLabel30.setText("Caja");

        jLabel31.setText("Masaje");

        jLabel32.setText("Tiempo");

        Agregar_Asientos.setText("Agregar");
        Agregar_Asientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_AsientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_asientosLayout = new javax.swing.GroupLayout(jd_asientos.getContentPane());
        jd_asientos.getContentPane().setLayout(jd_asientosLayout);
        jd_asientosLayout.setHorizontalGroup(
            jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_asientosLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel30)
                    .addComponent(jLabel29)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_asientosLayout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel28)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_asientosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(masaje_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(caja_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(material_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tiempo_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(181, 181, 181))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_asientosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Agregar_Asientos)
                .addGap(57, 57, 57))
        );
        jd_asientosLayout.setVerticalGroup(
            jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_asientosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel28)
                .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_asientosLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel29)
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_asientosLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(material_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(caja_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addGap(17, 17, 17)
                .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masaje_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jd_asientosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(tiempo_Asientos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(Agregar_Asientos)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel33.setText("Escoger Partes del Vehiculo");

        jt_Bateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Autonomia", "Material", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jt_Bateria);

        jt_Inferior.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Material", "Caja", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jt_Inferior);

        jt_Carroceria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Maletero", "Tiempo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(jt_Carroceria);

        jLabel34.setText("Baterias");

        jLabel35.setText("Carroceria");

        jLabel36.setText("Interior");

        jLabel37.setText("VIN");

        jLabel38.setText("Marca Audio");

        jLabel39.setText("Color");

        jLabel40.setText("Cantidad Asientos");

        AgregarCarro.setText("AGREGAR");
        AgregarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_CrearCarroLayout = new javax.swing.GroupLayout(jd_CrearCarro.getContentPane());
        jd_CrearCarro.getContentPane().setLayout(jd_CrearCarroLayout);
        jd_CrearCarroLayout.setHorizontalGroup(
            jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(272, 272, 272))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(282, 282, 282))))
            .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                .addGap(392, 392, 392)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(AgregarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                                    .addComponent(jLabel40)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                                    .addComponent(asientos_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                                    .addComponent(jLabel38)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(marca_Audio, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                                    .addComponent(jLabel39)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(color_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                                .addComponent(jLabel37)
                                .addGap(192, 192, 192)
                                .addComponent(vin_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                        .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(77, 77, 77))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(272, 272, 272))))
        );
        jd_CrearCarroLayout.setVerticalGroup(
            jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel33)
                .addGap(37, 37, 37)
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel35)
                        .addGap(0, 0, 0)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                        .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel37)
                                    .addComponent(vin_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 101, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(color_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel39))))
                        .addGap(45, 45, 45)
                        .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel38)
                            .addComponent(marca_Audio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(88, 88, 88)
                        .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(asientos_Vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jd_CrearCarroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_CrearCarroLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_CrearCarroLayout.createSequentialGroup()
                        .addComponent(AgregarCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addGap(50, 50, 50))
        );

        jt_Vehiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "VIN", "COLOR", "BATERIA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(jt_Vehiculo);

        jt_Esamblador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "ESAMBLADOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane10.setViewportView(jt_Esamblador);

        jLabel41.setText("Esamblar");

        esamblar_Carro.setText("Esamblar");
        esamblar_Carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                esamblar_CarroActionPerformed(evt);
            }
        });

        eliminar.setText("Eliminar");
        eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_EsamblarLayout = new javax.swing.GroupLayout(jd_Esamblar.getContentPane());
        jd_Esamblar.getContentPane().setLayout(jd_EsamblarLayout);
        jd_EsamblarLayout.setHorizontalGroup(
            jd_EsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EsamblarLayout.createSequentialGroup()
                .addGroup(jd_EsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_EsamblarLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(jd_EsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jd_EsamblarLayout.createSequentialGroup()
                                .addComponent(esamblar_Carro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eliminar)
                                .addGap(18, 18, 18))))
                    .addGroup(jd_EsamblarLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel41)))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        jd_EsamblarLayout.setVerticalGroup(
            jd_EsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_EsamblarLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel41)
                .addGap(81, 81, 81)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jd_EsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(esamblar_Carro)
                    .addComponent(eliminar))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jLabel42.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        jLabel42.setText("Carro Ensamblando");

        javax.swing.GroupLayout HiloEsamblarLayout = new javax.swing.GroupLayout(HiloEsamblar.getContentPane());
        HiloEsamblar.getContentPane().setLayout(HiloEsamblarLayout);
        HiloEsamblarLayout.setHorizontalGroup(
            HiloEsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HiloEsamblarLayout.createSequentialGroup()
                .addGroup(HiloEsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HiloEsamblarLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(prog_Esamblar, javax.swing.GroupLayout.PREFERRED_SIZE, 560, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HiloEsamblarLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jLabel42)))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        HiloEsamblarLayout.setVerticalGroup(
            HiloEsamblarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HiloEsamblarLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel42)
                .addGap(126, 126, 126)
                .addComponent(prog_Esamblar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("TOYOTA");

        Crearvehicuos.setText("Agregar");
        Crearvehicuos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearvehicuosActionPerformed(evt);
            }
        });

        jLabel2.setText("Vehiculos");

        ListaDeVehiculos.setText("Esamblar");
        ListaDeVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ListaDeVehiculosActionPerformed(evt);
            }
        });

        jLabel3.setText("Ensambladores");

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Partes");

        jButton2.setText("Bateria");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Carroceria");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Interior");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Audio");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Asientos");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(52, 52, 52)
                                .addComponent(Crearvehicuos, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButton2)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(ListaDeVehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton6))
                                .addGap(64, 64, 64)
                                .addComponent(jButton4)))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Crearvehicuos)
                    .addComponent(ListaDeVehiculos)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jButton1))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(155, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearvehicuosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearvehicuosActionPerformed
        jd_CrearCarro.setModal(true);
        jd_CrearCarro.pack();
        jd_CrearCarro.setLocationRelativeTo(this);
        jd_CrearCarro.setVisible(true);


    }//GEN-LAST:event_CrearvehicuosActionPerformed

    private void edad_EsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edad_EsambladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edad_EsambladorActionPerformed

    private void AgregarEnsambladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEnsambladorActionPerformed
        try {
            int id = Integer.parseInt(id_Esamblador.getText());
            String nombre = nombre_Esamblador.getText();
            String genero = genero_Esamblador.getText();
            int edad = Integer.parseInt(edad_Esamblador.getText());

            Esamblador e = new Esamblador(id, nombre, genero, edad, 0);
            ac.cargarArchivo();
            ac.getEsamblador().add(e);
            ac.escribirArchivo();

            id_Esamblador.setText("");
            nombre_Esamblador.setText("");
            genero_Esamblador.setText("");
            edad_Esamblador.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_AgregarEnsambladorActionPerformed

    private void agregar_BateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_BateriaActionPerformed
        try {
            String autonomia = autonomia_Bateria.getText();
            String material = material_Bateria.getText();
            int tiempo = Integer.parseInt(tiempo_Bateria.getText());

            bateria.add(new Bateria(autonomia, material, tiempo));

            autonomia_Bateria.setText("");
            material_Bateria.setText("");
            tiempo_Bateria.setText("");

            Object[] servicio = {autonomia, material, tiempo};
            DefaultTableModel modelo = (DefaultTableModel) jt_Bateria.getModel();
            modelo.addRow(servicio);
            jt_Bateria.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_agregar_BateriaActionPerformed

    private void agregar_CarroceriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_CarroceriaActionPerformed
        try {
            String tipo = tipo_carroceria.getText();
            int capacidad = Integer.parseInt(maletero_capacidad.getText());
            int tiempo = Integer.parseInt(tiempo_carroceria.getText());

            carroc.add(new Carroceria(tipo, capacidad, tiempo));

            tipo_carroceria.setText("");
            maletero_capacidad.setText("");
            tiempo_carroceria.setText("");

            Object[] servicio = {tipo, capacidad, tiempo};
            DefaultTableModel modelo = (DefaultTableModel) jt_Carroceria.getModel();
            modelo.addRow(servicio);
            jt_Carroceria.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_agregar_CarroceriaActionPerformed

    private void agregar_InteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_InteriorActionPerformed
        try {
            String material = material_Interior.getText();
            String volante = Volante_Interior.getText();
            int botones = Integer.parseInt(botones_Interior.getText());
            int tiempo = Integer.parseInt(tiempo_interior.getText());

            interior.add(new Interior(material, volante, botones, tiempo));

            Object[] servicio = {material, volante, tiempo};
            DefaultTableModel modelo = (DefaultTableModel) jt_Inferior.getModel();
            modelo.addRow(servicio);
            jt_Inferior.setModel(modelo);

            material_Interior.setText("");
            Volante_Interior.setText("");
            botones_Interior.setText("");
            tiempo_interior.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_agregar_InteriorActionPerformed

    private void agregar_InfoentretenimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregar_InfoentretenimientoActionPerformed
        try {
            int pantallas = Integer.parseInt(pantallas_Infoentre.getText());
            String visor = "";
            if (si.isSelected()) {
                visor.equals("SI");
            } else if (no.isSelected()) {
                visor.equals("no");
            }
            int ancho = Integer.parseInt(ancho_infoentre.getText());
            int timpo = Integer.parseInt(tiempo_infoentre.getText());

            sistema.add(new Sistema(pantallas, visor, ancho, timpo));

            pantallas_Infoentre.setText("");
            ancho_infoentre.setText("");
            tiempo_infoentre.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_agregar_InfoentretenimientoActionPerformed

    private void siActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siActionPerformed

    private void Agregar_AsientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_AsientosActionPerformed

        String material = material_Asientos.getText();
        String caja = caja_Asientos.getText();
        String masaje = masaje_Asientos.getText();
        int tiempo = Integer.parseInt(tiempo_Asientos.getText());

        asientos.add(new Asientos(material, caja, masaje, tiempo));

        material_Asientos.setText("");
        caja_Asientos.setText("");
        masaje_Asientos.setText("");
        tiempo_Asientos.setText("");


    }//GEN-LAST:event_Agregar_AsientosActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Jd_Bateria.setModal(true);
        Jd_Bateria.pack();
        Jd_Bateria.setLocationRelativeTo(this);
        Jd_Bateria.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jd_Carroceria.setModal(true);
        jd_Carroceria.pack();
        jd_Carroceria.setLocationRelativeTo(this);
        jd_Carroceria.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jd_Interior.setModal(true);
        jd_Interior.pack();
        jd_Interior.setLocationRelativeTo(this);
        jd_Interior.setVisible(true);


    }//GEN-LAST:event_jButton4ActionPerformed

    private void AgregarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCarroActionPerformed
        try {
            String vin = vin_vehiculo.getText();
            String color = color_vehiculo.getText();
            String audio = marca_Audio.getText();
            int asientos = Integer.parseInt(asientos_Vehiculo.getText());

            int poci = jt_Bateria.getSelectedRow();
            int poci2 = jt_Carroceria.getSelectedRow();
            int poci3 = jt_Inferior.getSelectedRow();

            for (int i = 0; i < bateria.size(); i++) {
                String bate = "";
                bate = bateria.get(poci).getMaterial();
            }
            for (int i = 0; i < carroc.size(); i++) {
                String carroceria = "";
                carroceria = carroc.get(poci2).getCarroceria();

            }
            for (int i = 0; i < interior.size(); i++) {
                String inte = "";
                inte = interior.get(poci3).getMaterial();

            }
            Vehiculo v = new Vehiculo(vin, color, audio, color, audio, audio, asientos);
            av.cargarArchivo();
            av.getVehiculo().add(v);
            av.escribirArchivo();

            vin_vehiculo.setText("");
            color_vehiculo.setText("");
            marca_Audio.setText("");
            asientos_Vehiculo.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_AgregarCarroActionPerformed

    private void ListaDeVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDeVehiculosActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) jt_Vehiculo.getModel();
        modelo.setRowCount(0);
        adminCreados av = new adminCreados("./Vehiculos.txt");
        av.cargarArchivo();
        for (int i = 0; i < av.getVehiculo().size(); i++) {
            String vin = av.getVehiculo().get(i).getVin();
            String color = av.getVehiculo().get(i).getColor();
            int asientos = av.getVehiculo().get(i).getAsientos();
            Object[] servicio = {vin, color, asientos};
            modelo.addRow(servicio);
        }
        jt_Vehiculo.setModel(modelo);
        DefaultTableModel model = (DefaultTableModel) jt_Esamblador.getModel();
        model.setRowCount(0);
        adminEsambladores ac = new adminEsambladores("./Esambladores.txt");
        ac.cargarArchivo();
        for (int i = 0; i < ac.getEsamblador().size(); i++) {
            String nombre = ac.getEsamblador().get(i).getNombre();
            int id = ac.getEsamblador().get(i).getId();
            int esamblados = ac.getEsamblador().get(i).getEsamblados();
            Object[] servicio = {nombre, id, esamblados};
            model.addRow(servicio);
        }
        jt_Esamblador.setModel(model);
        jd_Esamblar.setModal(true);
        jd_Esamblar.pack();
        jd_Esamblar.setLocationRelativeTo(this);
        jd_Esamblar.setVisible(true);


    }//GEN-LAST:event_ListaDeVehiculosActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        jd_Audio.setModal(true);
        jd_Audio.pack();
        jd_Audio.setLocationRelativeTo(this);
        jd_Audio.setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jd_asientos.setModal(true);
        jd_asientos.pack();
        jd_asientos.setLocationRelativeTo(this);
        jd_asientos.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jd_Esambladores.setModal(true);
        jd_Esambladores.pack();
        jd_Esambladores.setLocationRelativeTo(this);
        jd_Esambladores.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void esamblar_CarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_esamblar_CarroActionPerformed
        try {
            HiloEsamblar.setModal(true);
            HiloEsamblar.pack();
            HiloEsamblar.setLocationRelativeTo(this);
            HiloEsamblar.setVisible(true);
            esam = new Esamblar(prog_Esamblar, orden, rootPaneCheckingEnabled, rootPaneCheckingEnabled);
            esam.setAvanzar(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }


    }//GEN-LAST:event_esamblar_CarroActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        try {
            if (jt_Vehiculo.getSelectedRow() >= 0) {
                int po = jt_Vehiculo.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) jt_Vehiculo.getModel();
                modelo.removeRow(po);
                jt_Vehiculo.setModel(modelo);
                adminCreados av = new adminCreados("./Vehiculos.txt");
                av.cargarArchivo();
                av.getVehiculo().remove(po);
                av.escribirArchivo();
            } else if (jt_Esamblador.getSelectedRow() >= 0) {
                int po = jt_Esamblador.getSelectedRow();
                DefaultTableModel modelo = (DefaultTableModel) jt_Esamblador.getModel();
                modelo.removeRow(po);
                jt_Esamblador.setModel(modelo);
                adminEsambladores ac = new adminEsambladores("./Esambladores.txt");
                ac.cargarArchivo();
                ac.getEsamblador().remove(po);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "OCURRIO UN ERROR");
        }
    }//GEN-LAST:event_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarCarro;
    private javax.swing.JButton AgregarEnsamblador;
    private javax.swing.JButton Agregar_Asientos;
    private javax.swing.JButton Crearvehicuos;
    private javax.swing.JDialog HiloEsamblar;
    private javax.swing.JDialog Jd_Bateria;
    private javax.swing.JButton ListaDeVehiculos;
    private javax.swing.JTextField Volante_Interior;
    private javax.swing.JButton agregar_Bateria;
    private javax.swing.JButton agregar_Carroceria;
    private javax.swing.JButton agregar_Infoentretenimiento;
    private javax.swing.JButton agregar_Interior;
    private javax.swing.JTextField ancho_infoentre;
    private javax.swing.JTextField asientos_Vehiculo;
    private javax.swing.JTextField autonomia_Bateria;
    private javax.swing.JTextField botones_Interior;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField caja_Asientos;
    private javax.swing.JTextField color_vehiculo;
    private javax.swing.JTextField edad_Esamblador;
    private javax.swing.JButton eliminar;
    private javax.swing.JButton esamblar_Carro;
    private javax.swing.JTextField genero_Esamblador;
    private javax.swing.JTextField id_Esamblador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JDialog jd_Audio;
    private javax.swing.JDialog jd_Carroceria;
    private javax.swing.JDialog jd_CrearCarro;
    private javax.swing.JDialog jd_Esambladores;
    private javax.swing.JDialog jd_Esamblar;
    private javax.swing.JDialog jd_Interior;
    private javax.swing.JDialog jd_asientos;
    private javax.swing.JTable jt_Bateria;
    private javax.swing.JTable jt_Carroceria;
    private javax.swing.JTable jt_Esamblador;
    private javax.swing.JTable jt_Inferior;
    private javax.swing.JTable jt_Vehiculo;
    private javax.swing.JTextField maletero_capacidad;
    private javax.swing.JTextField marca_Audio;
    private javax.swing.JTextField masaje_Asientos;
    private javax.swing.JTextField material_Asientos;
    private javax.swing.JTextField material_Bateria;
    private javax.swing.JTextField material_Interior;
    private javax.swing.JRadioButton no;
    private javax.swing.JTextField nombre_Esamblador;
    private javax.swing.JTextField pantallas_Infoentre;
    private javax.swing.JProgressBar prog_Esamblar;
    private javax.swing.JRadioButton si;
    private javax.swing.JTextField tiempo_Asientos;
    private javax.swing.JTextField tiempo_Bateria;
    private javax.swing.JTextField tiempo_carroceria;
    private javax.swing.JTextField tiempo_infoentre;
    private javax.swing.JTextField tiempo_interior;
    private javax.swing.JTextField tipo_carroceria;
    private javax.swing.JTextField vin_vehiculo;
    // End of variables declaration//GEN-END:variables

    adminEsambladores ac = new adminEsambladores("./Esambladores.txt");
    adminCreados av = new adminCreados("./Vehiculos.txt");
    ArrayList<Bateria> bateria = new ArrayList();
    ArrayList<Carroceria> carroc = new ArrayList();
    ArrayList<Interior> interior = new ArrayList();
    ArrayList<Sistema> sistema = new ArrayList();
    ArrayList<Asientos> asientos = new ArrayList();
    Orden orden;
    Esamblar esam;

}
